### ISSUE TITLE
Crash when launching with forge

### ISSUE THREAD

**Issue by KeinNiemand** [ameisen/jdk-mc#4]
Game Crashes on launch 
Minecraft version: 1.12.2
Forge Version: 14.23.5.2854
Crashlog:
`MultiMC version: 0.6.12-develop-1481

Minecraft folder is:
A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/instances/1.12.2 Forge Test/.minecraft

Java path is:
A:/Minecraft/Java/Minecraft jdk 15/bin/javaw.exe

Checking Java version...
Java is version 15-release, using 64-bit architecture, from Digital Carbide.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/instances/1.12.2 Forge Test/natives

Libraries:
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/instances/1.12.2 Forge Test/.minecraft --assetsDir A:/Minecraft/Minecraft NEu/MultiMC/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1536m, -Xmx8192m, -Duser.language=en]

Minecraft Prozess ID: 5720

Using onesix launcher.

[14:50:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:50:09] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[14:50:09] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 15-release, running on Windows 10:amd64:10.0, installed at A:\Minecraft\Java\Minecraft jdk 15
[14:50:09] [main/INFO] [FML]: Searching A:\Minecraft\Minecraft NEu\MultiMC\MultiMC\instances\1.12.2 Forge Test\.minecraft\mods for mods
[14:50:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:50:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:50:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:50:11] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:50:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:50:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:50:11] [main/FATAL] [FML]: A CRITICAL PROBLEM OCCURRED INITIALIZING MINECRAFT - LIKELY YOU HAVE AN INCORRECT VERSION FOR THIS FML
[14:50:11] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.Loader
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:67) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.Loader
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:468) ~[?:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 10 more
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/RemappingClassAdapter
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1058) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:568) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:438) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:432) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:431) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:75) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:468) ~[?:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.RemappingClassAdapter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:570) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1058) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:568) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:438) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:432) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:691) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:431) ~[?:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:75) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:468) ~[?:?]
	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:56) ~[forge-1.12.2-14.23.5.2854-universal.jar:?]
	... 10 more
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.lang.SecurityManager.checkExit(SecurityManager.java:620)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.lang.Runtime.exit(Runtime.java:113)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.base/java.lang.System.exit(System.java:1769)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:50:11] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[14:50:11] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.lang.SecurityManager.checkExit(SecurityManager.java:620)
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.lang.Runtime.exit(Runtime.java:113)
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.lang.System.exit(System.java:1769)
[14:50:11] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Der Prozess wurde mit Status 1 beendet.
Clipboard copy at: 30 Oct 2020 14:50:22 +0100`

**Comment by ameisen** [comment]
My local build resolves launch issues with older versions (< 1.15) and Forge. These were caused by dependency on libraries that themselves had dependencies in the JVM regarding reflection which were no longer being satisfied. Those have been rectified, but I will not mark this as 'fixed' until I publish a new version for testing.

There are further issues with some modpacks on 1.12 which include a huge number of dependencies, which themselves depend on a lot of behavior in the JVM that has either changed or has been deprecated/removed. I have resolved *some* of those, but not all of them. `javax` and so forth are still needing to be ported but it's frustrating as it tends to break the module build orders.

Some of my optimization work will require embedding custom versions of some libraries which may break backwards compatibility in some cases as well. I'm still investigating this.

**Comment by ameisen** [comment]
Some of the compatibility issues here have been resolved, but not all of them. Once `javax` is fully forward-ported I'll be more comfortable closing this.
